import Navbar from "@/ui/layout/Navbar/Navbar";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ReduxProvider } from "@/redux/provider";
import Footer from "@/ui/layout/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <ReduxProvider>
        <body className="relative">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={true}
            storageKey="theme"
          >
            <Navbar />
            <div className="min-h-screen bg-white dark:bg-primary">
              {children}
            </div>
          </ThemeProvider>
        </body>
      </ReduxProvider>
    </html>
  );
}
